### ISSUE TITLE
sparta_panner crashing when number of Outputs is set to 0

### ISSUE THREAD

**Issue by DearRealityMax** [leomccormack/SPARTA#1]
reproduction procedure:
- insert sparta_panner on empty track with 10 channels
- select output preset for 9.x
- slide "N Chan"- slider to 0

Environment:
Reaper 5.70
macOS 10.13.6

--> I could help fixing the bug if you'd like to

**Comment by leomccormack** [comment]
Thanks for letting me know. 

The plugin should now correctly identify that a 9.x setup, when reduced to 2 loudspeakers, is actually 2 dimensional. And the minimum number of loudspeakers is now set to 2 to avoid the crash.
