### ISSUE TITLE
Installation on Linux

### ISSUE THREAD

**Issue by alastairhmoore** [leomccormack/SPARTA#12]
Trying to install Linux_SPARTA_2020_02_10_v1.3.4 downloaded from web onto Ubuntu 18.0.4 LTS (64-bit) with Reaper v6.09. Reaper finds the plugins but cam't load them. They all report...

```
swell: dlopen() failed: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/lib/aalto_plugins/sparta_ambiENC.so)
```
I found this issue reported [https://forum.juce.com/t/glibc-2-29-not-found-on-ubuntu-18-04/34960/7](https://forum.juce.com/t/glibc-2-29-not-found-on-ubuntu-18-04/34960/7) which looks relevant. I haven't tried compiling from source myself.

**Comment by leomccormack** [comment]
Hi, I've not come across this problem myself, although, the upcoming JUCE version 6 looks to be much better behaved on Linux. I've just uploaded some early juce6 builds here, incase this fixes the problem and you're willing to try them out:
http://research.spa.aalto.fi/projects/sparta_vsts/download/Linux_SPARTA_2020_05_31_v1.4.2-juce6.zip

Note also that if you want to compile them yourself, I would recommend using the SPARTA/juce6 branch, follow the customMKLinstructions from the Spatial_Audio_Framework/develop branch, and build the plugins via the excellent new build shell scripts by Marc Lavallee :- )

**Comment by ariutti** [comment]
Hi guys, same problem here on a Ubuntu Studio machine with these characteristics
```
  Operating System: Ubuntu 18.04.5 LTS
            Kernel: Linux 4.15.0-162-lowlatency
      Architecture: x86-64
```
and Reaper v6.05 rev 527eef (Mar 5 2020).

Reaper says:
`swell: dlopen() failed: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/nicola/plugins/Linux_SPARTA_2021_11_22_v1.5.2/libsparta_panner.so)
`
