### ISSUE TITLE
error in linux install instructions

### ISSUE THREAD

**Issue by madskjeldgaard** [leomccormack/SPARTA#19]
hi just noticed a typo in the install instructions for linux:
```
sudo cp saf_mkl_custom.so /usr/lib
```
should be
```
sudo cp libsaf_mkl_custom.so /usr/lib
```

**Comment by leomccormack** [comment]
Hi, good catch! 

Although the following install script from the develop branch will soon replace these instructions (also making the process a bit easier :) 
https://github.com/leomccormack/Spatial_Audio_Framework/blob/develop/scripts/install-safmkl.sh

**Comment by madskjeldgaard** [comment]
Nice ! Thanks!




On Mon, Sep 21, 2020 at 8:55 PM +0200, "Leo McCormack" <notifications@github.com> wrote:















Hi, good catch!


Although the following install script from the develop branch will soon replace these instructions (also making the process a bit easier :)

https://github.com/leomccormack/Spatial_Audio_Framework/blob/develop/scripts/install-safmkl.sh
