### ISSUE TITLE
Automation bugs in panner

### ISSUE THREAD

**Issue by mrlimbic** [leomccormack/SPARTA#2]
I just tested panner in reaper with some automation and noticed a few quirks.

The puck doesn't move to follow the values, even though the values change at the side.

Also write automation by using puck doesn't work. It continues to read. So can only hand draw automation.

Also the parameter naming seems off by one with first name appearing twice. See screenshot.

<img width="330" alt="screen shot 2019-01-06 at 15 05 03" src="https://user-images.githubusercontent.com/837315/50737903-d453c500-11c5-11e9-8c2d-055dfcc6ac61.png">

Looking at the code for parameter naming it seems odd to me.

Why is uneven or zero used? Is parameter 0 a special case?

```
const String PluginProcessor::getParameterName (int index)
{
    if (index % 2 || index == 0)
        return TRANS("Azim_") + String(index/2);
    else
        return TRANS("Elev_") + String((index-1)/2);
}

const String PluginProcessor::getParameterText(int index)
{
    if (index % 2 || index == 0)
        return String(panner_getSourceAzi_deg(hPan, index/2));
    else
        return String(panner_getSourceElev_deg(hPan, (index-1)/2));
}

```

**Comment by leomccormack** [comment]
Hey! Thanks for letting me know. I don't remember my logic behind that code either :D 
I've now rewritten it, so no more duplication of the first parameter in the automation list, and the panning window now correctly refreshes (as does ambiENC and the Binauraliser).

As for the automation learning, I fear this is no quick fix, as it requires me rewriting the default UI code, but it's on my todo list.

Thanks again!
