### ISSUE TITLE
Linux version lagging behind

### ISSUE THREAD

**Issue by madskjeldgaard** [leomccormack/SPARTA#21]
Hi 
sorry for the issue spamming :) 
I noticed that the linux version of the plugins downloadable on the website are a few versions behind the other ones (1.3.4 vs 1.4.1). 
Best!

**Comment by leomccormack** [comment]
Working on it : )

**Comment by madskjeldgaard** [comment]
Thanks !




On Tue, Sep 29, 2020 at 5:20 PM +0200, "Leo McCormack" <notifications@github.com> wrote:















Closed #21.
