### ISSUE TITLE
Linux binary compat (gtk, webkit)

### ISSUE THREAD

**Issue by x42** [leomccormack/SPARTA#22]
Currently JUCE dynamically links again in gtk-webit by default.  This does not only produce binaries that may  not be redistributable, but it also results in a dependency on gtk3 (and 20+ indirect dependent libs).

Due to the gtk3 dependency the plugins will not load in Ardour (or Harrison Mixbus).

Please consider adding `JUCE_WEB_BROWSER="0"` to `<JUCEOPTIONS>` in **all** *.jucer files.

e.g replace https://github.com/leomccormack/SPARTA/blob/dfd3becddb30effeb2008b5f874a5c05b8856468/audio_plugins/_SPARTA_ambiDRC_/sparta_ambiDRC.jucer#L347
```
<JUCEOPTIONS JUCE_QUICKTIME="disabled" JUCE_USE_CAMERA="disabled" JUCE_WEB_BROWSER="0"/>
```

**Comment by leomccormack** [comment]
Hi! I was unaware of this issue with Ardour so thanks for letting me know!

The latest SPARTA release binaries were built via CMake though, which apparently already has this JUCE_WEB_BROWSER=0 flag in the lists:
[https://github.com/leomccormack/SPARTA/blob/master/audio_plugins/_SPARTA_ambiBIN_/CMakeLists.txt](https://github.com/leomccormack/SPARTA/blob/master/audio_plugins/_SPARTA_ambiBIN_/CMakeLists.txt)

Do these released binaries still cause a problem in Ardour? 

In any case, I can disable JUCE_WEB_BROWSER also in the jucer files, no problem. I don't believe it is needed at all. Actually, I wonder what other unnecessary options I have enabled! Perhaps some belated spring cleaning is in order...

Thanks again!

**Comment by leomccormack** [comment]
OK! JUCE_WEB_BROWSER is now disabled for all .jucer projects. Please re-open the issue if the problem persists.

**Comment by x42** [comment]
Thank you!

SPARTA release binaries  (here Linux 64bit) don't work on debian/stable (libm.so.6: version `GLIBC_2.29' not found) so I cannot test those.
