### ISSUE TITLE
Magnitude of Velocity vector in AmbiDEC

### ISSUE THREAD

**Issue by gsenna** [leomccormack/SPARTA#24]
Hi,

I am testing different Ambisonics decoders for a 2D regular quad array of loudspeakers. I measured the MMD decoder in AmbiDEC and I see that the resulting rV magnitude is 1.5 instead of 1. In fact all the decoders other than the AllRAD gave me that magnitude. Could there be a bug somewhere inside the SAF? I know it could also be my measuring method, but I also measured the decoding matrix returned by the PINV method within the [Ambisonics Decoder Toolbox](https://bitbucket.org/ambidecodertoolbox/adt/src/master/) and that one is correct (rV=1). You can try the attached JSON file using IEM's SimpleDecoder.

Thank you very much for the SPARTA Suite!
[quad_1o_adt.json.zip](https://github.com/leomccormack/SPARTA/files/5532809/quad_1o_adt.json.zip)

Regards.

**Comment by chris-hld** [comment]
(Possibly related: scaling conventions in decoders not consistent, WIP: https://github.com/leomccormack/Spatial_Audio_Framework/pull/7)

**Comment by jinnsjj** [comment]
I have a guess, this may because you are using a 2D array, ambisonic decoder has different gains in 2D and 3D case and SPARTA doesn't consider 2D case (possibly). Try a 3D array may give you the proper magitude.

**Comment by gsenna** [comment]
Hi,

Trying to follow up on this. I think now I partially know what's going on. I found inside the SAF the following comment:

`Note that the MMD and EPAD decoding options revert back to "SAD" if the loudspeakers are uniformly distributed on the sphere`

But doesn't that fact only makes sense for special cases of loudspeaker designs (i.e., platonic solids)? I know from experience that a regular 2D quad speaker array [45 0;-45 0;135 0; -135 0] has different SAD and MMD matrices associated. Isn't this right? Given that fact, I think it would be nice if there was a possibility for the ambiDEC plugin to make use of the correct matrix for the chosen decoding method.

Thanks!

**Comment by gsenna** [comment]
Finally found out what's going on. @jinnsjj was right. [SAF adds two more speakers](https://github.com/leomccormack/Spatial_Audio_Framework/blob/master/examples/src/ambi_dec/ambi_dec.c#L232-L248) [0 90; 0 -90] when the loudspeaker array is 2D and this is what is distorting the decoding matrices.

As per the comment in my previous reply this will make 1st order SAD and MMD matrices equal for a square array. However, even with the addition of the 2 speakers mentioned above, a 3rd order MMD matrix will be different than the SAD one for an octagon. So it is not always true that uniformly distributed arrays will make the MMD option "revert back to SAD".

**Comment by jinnsjj** [comment]
My understanding is:
MMD and SAD matrix are both a matrix of spherical harmonics at loudspeakers positions, and MMD is the inverse of SAD, so when the array is uniform, they are equal.
EPAD is a kind of SAD with compensation when the array is not uniform to keep the energy from all directions consistent. so when the array is uniform, they are equal as well.
In your case, an octagon array with two imaginary loudspeaker is not a uniform array (dense at horizon plane but sparse at top and bottom). You can try a t-design 3D array to validate it.

**Comment by gsenna** [comment]
I think you are right. But I hope in future versions of ambiDEC there is the possibility to use the MMD decoder without those two extra speaker being added surreptitiously. Turns out it is not so easy to find cross-platform 2-band HOA MMD decoders for regular 2D arrays in a ready-to-use VST.

**Comment by leomccormack** [comment]
ah ok! I'm now understanding the problem better. Apologies, it's been quite a while since many of these SAF examples were written.

For the loudspeaker decoding functions in saf_hoa, this statement still holds true:
> Note that the MMD and EPAD decoding options revert back to "SAD" if the loudspeakers are uniformly distributed on the sphere

There is actually a unit test in SAF for saf_hoa which asserts this behaviour when using a number of different t-design distributions of loudspeakers.

The addition of the 2 +/- 90degrees elevation virtual loudspeakers in ambi_dec was to make sure that the AllRAD solution (which assumes 3D) would never fail when computing the VBAP gains. The above statement still holds true, however, for the ambi_dec example, but with the key phrase being "on the sphere". However, since these virtual loudspeakers are indeed not needed for the other decoding options, I've now changed the example to only add them for AllRAD. 

Thank you for bringing this to my attention :) 
... and please accept by apologies for being so slow.
