### ISSUE TITLE
Feature request:  VST3

### ISSUE THREAD

**Issue by magnetophon** [leomccormack/SPARTA#28]
The VST2 SDK cannot legally be distributed anymore.
A VST3 port would be great!

**Comment by leomccormack** [comment]
hi, building the plugins as VST3 is already possible. However, unfortunately, switching from VST2 to VST3 would be a step back in terms of being able to flexibly change the channel layouts and would restrict the maximum number of channels:
- https://github.com/steinbergmedia/vst3sdk/issues/28
- https://sdk.steinberg.net/viewtopic.php?f=4&t=549
- https://sdk.steinberg.net/viewtopic.php?f=4&t=624

Basically, the SPARTA VST2 plugins support up to 64 channels (7th order Ambisonics), whereas the VST3 versions would instead support only up to 24 channels (3rd order Ambisonics), which is a significant downgrade.

While Steinberg appear to be content with their self-imposed limitation for their own plugins, we are unable to do so as we frequently use these plugins with loudspeaker arrays comprising more than 24 channels (and 4th order+) for our research and for teaching. 

If the VST3 SDK is updated, or a VST4 SDK comes along, which restores the features of the VST2 SDK then we are happy to switch. However, until then, the VST2 SDK can be downloaded from, e.g.:
- https://web.archive.org/web/20181016150224/https://download.steinberg.net/sdk_downloads/vstsdk3610_11_06_2018_build_37.zip

**Comment by magnetophon** [comment]
Thanks for the quick reply.

> building the plugins as VST3 is already possible.

How?

**Comment by leomccormack** [comment]
by the power of JUCE ;) 
In the .jucer file settings you can tick also: VST3, AU, AAX, Unity,  etc. As long as you then also link the respective SDKs, the generated VSsolutions/Xcode Projects/makefiles should build them too. 

Alternatively, if using CMake, you can change the CMakeLists FORMAT settings, to include the other plugin formats. E.g.
https://github.com/leomccormack/SPARTA/blob/master/audio_plugins/_SPARTA_ambiBIN_/CMakeLists.txt
line 19 can be set to:
FORMAT             VST VST3

**Comment by magnetophon** [comment]
Thank you!
