### ISSUE TITLE
Building error using openBlas

### ISSUE THREAD

**Issue by wayne391** [leomccormack/SPARTA#29]
Hi, thanks for the awesome project!
I want to use OpenBlas so I followed the instructions [here](https://github.com/leomccormack/Spatial_Audio_Framework/blob/master/docs/PERFORMANCE_LIBRARY_INSTRUCTIONS.md#saf_use_open_blas_and_lapacke). To run on MAC, I built OpenBlas via CMake. I also added the following lines in `Header Search Paths` in the Projucer.

```
<path>/OpenBLAS/lapack-netlib/CBLAS/include
<path>/OpenBLAS/lapack-netlib/LAPACKE/include
```

But I got this error:

```
Undefined symbol: _LAPACKE_sgetrf
Undefined symbol: _LAPACKE_sgetri
```

How to fix it?

**Comment by leomccormack** [comment]
Hi! I must be honest, it's been a while since I used OpenBLAS with Mac. Is it just these two functions it can't find? 
Also, is there a reason that you don't want to use the native Apple Accelerate option? (no compilation required! :)
