### ISSUE TITLE
install-juce.sh can't detect JUCE 6 to compile it as GPL

### ISSUE THREAD

**Issue by marclava** [leomccormack/SPARTA#30]
## Description

Search path is wrong to find the licensing file of JUCE version 6, when using the install-juce.sh script

## Environment

1. OS: Ubuntu 20.04

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Run "audio_plugins/install-juce.sh" to fetch and build JUCE with its Projucer app
2. Start "SDKs/Projucer"
3. Notice that the compiled JUCE version is not GPL

## Expected Output

line 88 of "SDKs/JUCE/extras/Projucer/Source/Application/UserAccount/jucer_LicenseState.h"
should be "Type type = Type::gpl;"

## Actual Output

line 88 of "SDKs/JUCE/extras/Projucer/Source/Application/UserAccount/jucer_LicenseState.h"
is "Type type = Type::none;"

## Additional information

I was too lazy to fork the code again for such a simple fix... Here's a patch:
[install-juce.patch.gz](https://github.com/leomccormack/SPARTA/files/6130211/install-juce.patch.gz)
(BTW I also uploaded this patch to the Spatial_Audio_Framework repo, it was a mistake)

**Comment by leomccormack** [comment]
Thanks!
