### ISSUE TITLE
Video support on Powermap plugin

### ISSUE THREAD

**Issue by theodupre** [leomccormack/SPARTA#33]
Is there a quick way to read a video file instead of a camera in the powermap visualization plugin in order to do off-line study and editing ? 
Thanks
Theo

**Comment by leomccormack** [comment]
hi! Not natively. But I am aware of some people we were able to host the video file on MaxMSP and then "trick" the powermap plugin into thinking this was a webcam. Otherwise, the visualiser plugins only support "live" video from webcams/360 cameras, unfortunately.

**Comment by theodupre** [comment]
For those who are interested, I managed to trick the plugin by broadcasting videos in a virtual camera. You can use free software like OBS (Open Broadcaster Software) to broadcast content as a virtual camera. Just note that the native virtual camera option wasn't working on my PC, I used an OBS plugin following the procedure here [https://obsproject.com/forum/resources/obs-virtualcam.949/](url).
