### ISSUE TITLE
Possible bug in quaternion OSC message parsing

### ISSUE THREAD

**Issue by firthm01** [leomccormack/SPARTA#35]
It looks like there may be a copy and paste error in the quaternion message handling code here. I haven't tested this, but just noticed it looked suspect whilst I was browsing through the code: (I'd expect the index to be 3 rather than 2 on both lines.)

https://github.com/leomccormack/SPARTA/blob/73293ca60f74fa19287c8ddf2fe320a5ec29230a/audio_plugins/_SPARTA_rotator_/src/PluginProcessor.cpp#L68-L69

**Comment by leomccormack** [comment]
Ah yes, well spotted!
