### ISSUE TITLE
Powermap plugin: Map Avg and Cov Avg parameters 

### ISSUE THREAD

**Issue by theodupre** [leomccormack/SPARTA#36]
Hi, 
Can you give precisions about what processing is done to average the powermap and the exact influence of Map Avg and Cov. Avg.  I imagine Cov. Avg is related to the length of the frame to estimate the covariance. What's the relation between frame length and parameter value ? 
I guess map average acts as an averaging filter with previous frames but I'm not sure. 

Regards, 

Théophile

**Comment by leomccormack** [comment]
Hi!

The plugin uses a 128 STFT hopsize and a 1024 sample block size, so the spatial covariance matrix is computed on this NChannels x 8   time-frequency block per frequency bin: SpatialCovMatrix = TFsignals^H * TFsignals

The Cov. averaging parameter is then doing (a one-pole filter):
currentSpatialCovMatrix = avg_coeff  * prevSpatialCovMatrix + (1-avg_coeff) * newSpatialCovMatrix

The map averaging parameter is then doing the same, but on the resulting (pre-interpolated) previous/new powermap images instead.

Either averaging approach is valid, but I no longer recall why we added both! We can probably get away with just removing the latter, and to be honest, while it works fine, this plugin's internal code is also quite old and could probably do with a refresh at some point; the underlying spatial audio framework is significantly more capable now than it was a few years ago... It's just finding the time to go through it again.
