### ISSUE TITLE
AmbiBIN crashes Reaper immediately upon insertion

### ISSUE THREAD

**Issue by hectorC** [leomccormack/SPARTA#37]
It seems that the latest version of Reaper crashes with the AmbiBIN plugin. I've tried clean reinstalling Sparta but it didn't fix it. This is what I see in the Windows logs (0xc0000005 is Access Violation):

Faulting application name: reaper.exe, version: 6.3.2.0, time stamp: 0x60e8499a
Faulting module name: sparta_ambiBIN.dll, version: 0.0.0.0, time stamp: 0x608047c2
Exception code: 0xc0000005
Fault offset: 0x0000000000424578
Faulting process id: 0x46dc
Faulting application start time: 0x01d778c9468dae78
Faulting application path: E:\Program Files\REAPER (x64)\reaper.exe
Faulting module path: C:\Program Files\Steinberg\VstPlugins\sparta_ambiBIN.dll
Report Id: 43f6ed4a-0970-457b-8939-ab7dc703a3b7
Faulting package full name: 
Faulting package-relative application ID:

**Comment by leomccormack** [comment]
Hi!
I just updated my Windows10 and MacOS machines also to the new reaper (v6.3.2). 
AmbiBIN (and the other plugins) appear to be working as normal. 

- Is there are more detailed crash log available?
- Are any other plugins (outside of the SPARTA suite) causing this same issue? 
- Does rolling back REAPER to a previous version solve the problem?

Best,
Leo

**Comment by hectorC** [comment]
Thank you Leo for your reply. To answer your questions:

- From what I found online, it seems that Reaper doesn't produce crash logs and for bug reports they just ask to provide what I included in my report, which is the log produced by Windows.
- I didn't try them all but from several I did, only AmbiBIN crashes. I use this plugin extensively and it never gave me any problems. It's just recently that it started happening so I assumed it could be related to the latest version of Reaper, but...
- I tried older versions of Reaper and all of them seem to also crash. 

The crash happens right at the moment when the IR data is being loaded. Are there extra IR files that get installed with Sparta, and if yes, where are they located? Maybe the file is not readable or something?

**Comment by leomccormack** [comment]
hmm, there's something weird going on. And I would guess that it's some interaction between JUCE and REAPER, rather than any internal initialisations. The default HRIRs are baked into the binaries to avoid any file reading problems, and I would expect any problems there to crash the plugin indiscriminately of the DAW. 

Is it possible to try and load the plugin only with the default UI? (bypassing the JUCE GUI at least)

**Comment by hectorC** [comment]
If I set Raper to use the Generic UI for VSTs, it still crashes Reaper.

On the other hand, if I set the plugin to load as a separate process, Reaper doesn't crash with both generic or VST UI, but the plugin is not functional and the UI either closes (using the VST UI) or the sliders are not operational (generic UI).

**Comment by hectorC** [comment]
I found out that the Binauraliser plugin also crashes. Here's a video showing my tests: https://1drv.ms/u/s!AtXbduLrHv5XyGNg2WJDEDQHofGb?e=haE2cj

**Comment by leomccormack** [comment]
hey. I've now tried the latest REAPER and SPARTA on 2 more Windows machines and I still can't reproduce the crash, and unfortunately, without a helpful stack trace, or the ability to reproduce the crash with a debugger attached, I don't really have many options. 

If rolling back REAPER to a version that previously worked, no longer works, then this is quite bizarre. Can you try fully uninstalling (including deleting any residual e.g. "User/App" files), and then re-installing? 

As for what ambi_bin and Binauraliser have in common, they both have a SOFA reader, which requires an external library. I would suspect this would be a potential issue, but then I see ambiDEC (which also has a SOFA reader) is loading OK with you. However, can you try enabling the "binauralise loudspeakers" option in ambiDEC? Also, the spreader plugin has a SOFA reader, does this plugin also crash for you?

**Comment by hectorC** [comment]
Both ambiDEC and Spreader work fine but... I found the source of the problem! I was trying to figure if I had installed any software between the time ambiBIN worked and when it stopped working, and one of those was DearVR Spatial Connect. Oddly enough, uninstalling it fixed the crashes. Very strange since it's an external application. The only related thing that is configured in Reaper is a control surface preset for OSC communication between the DearVR Pro VST and the external VR app. I wonder if the issue had something to do with OSC...

**Comment by leomccormack** [comment]
Interesting! sparta_rotator, compass_binaural, compass_binauralVR, cropac_binaural, and hodirac_binaural are the other plugins that use OSC. If they also crash REAPER, then it could very well be some strange juce_osc module interaction. If you still can, please check these as well. In any case, it's good to know there's at least some sort of "fix" for this problem if anyone else encounters this. 
Sorry for the trouble!
