### ISSUE TITLE
Panner.. Is it possible to alter the influence of a speaker?

### ISSUE THREAD

**Issue by mrlimbic** [leomccormack/SPARTA#4]
Panner.. Is it possible to alter the influence of a speaker?

i.e in 5.1 you may want the center speaker to only have 50% influence (bleeds). 100% would be normal behaviour. 0% would be ignore that speaker completely (so only nearest left/right would be used).

Thanks.

**Comment by leomccormack** [comment]
Hi,
I understand that is this common behaviour for 5p1 panners, however, this would be quite difficult to extend to the arbitrary output configurations which sparta_panner supports. 
One solution, in this case, would be to use a separate matrix multiplier plugin post-panner, which could be configured as such: input centre channel attenuated, but boosted for left+right channels on output. I'll look into it. : )

**Comment by mrlimbic** [comment]
Separate matrix is a good idea. Also useful for compensation in situation where non identical powered speakers are used.
