### ISSUE TITLE
Compiling problem on Debian: "error: ‘ambi_enc_setSourceSolo’" & "error: ‘ambi_enc_setUnSolo’"

### ISSUE THREAD

**Issue by ilmarikoria** [leomccormack/SPARTA#41]
Hey! Ran into the following problem when compiling in Debian. Thanks!

 - System: Debian 10
 - Cmake options: "cmake -DSAF_PERFORMANCE_LIB=SAF_USE_OPEN_BLAS_AND_LAPACKE=1"
 - Ran both "install-juce.sh" and "install-vst2_sdk.sh" without issue.

> /home/ilmari/Downloads/SPARTA/audio_plugins/_SPARTA_ambiENC_/src/pannerView.cpp:191:17: error: ‘ambi_enc_setSourceSolo’ was not declared in this scope
                 ambi_enc_setSourceSolo(hAmbi, i);
                 ^~~~~~~~~~~~~~~~~~~~~~
/home/ilmari/Downloads/SPARTA/audio_plugins/_SPARTA_ambiENC_/src/pannerView.cpp:191:17: note: suggested alternative: ‘ambi_enc_setNumSources’
                 ambi_enc_setSourceSolo(hAmbi, i);
                 ^~~~~~~~~~~~~~~~~~~~~~
                 ambi_enc_setNumSources
/home/ilmari/Downloads/SPARTA/audio_plugins/_SPARTA_ambiENC_/src/pannerView.cpp: In member function ‘virtual void pannerView::mouseUp(const juce::MouseEvent&)’:
/home/ilmari/Downloads/SPARTA/audio_plugins/_SPARTA_ambiENC_/src/pannerView.cpp:221:9: error: ‘ambi_enc_setUnSolo’ was not declared in this scope
         ambi_enc_setUnSolo(hAmbi);
         ^~~~~~~~~~~~~~~~~~
/home/ilmari/Downloads/SPARTA/audio_plugins/_SPARTA_ambiENC_/src/pannerView.cpp:221:9: note: suggested alternative: ‘ambi_enc_setChOrder’
         ambi_enc_setUnSolo(hAmbi);
         ^~~~~~~~~~~~~~~~~~
         ambi_enc_setChOrder
make[2]: *** [audio_plugins/_SPARTA_ambiENC_/CMakeFiles/sparta_ambiENC.dir/build.make:93: audio_plugins/_SPARTA_ambiENC_/CMakeFiles/sparta_ambiENC.dir/src/pannerView.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1328: audio_plugins/_SPARTA_ambiENC_/CMakeFiles/sparta_ambiENC.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by ilmarikoria** [comment]
Ok, my mistake, I used the wrong configure options!

**Comment by leomccormack** [comment]
Hey! Apologies, I wasn't sure if this was still an issue.

I suspect that the problem is that the submodules haven't been updated with:
`git submodule update`

But please let me know if this is not the case : )
