### ISSUE TITLE
AmbiBIN doesn't keep the SOFA files loaded in the list after closing the UI (Reaper)

### ISSUE THREAD

**Issue by sguyader** [leomccormack/SPARTA#45]
If I select a sofa HRIR in AmbiBIN, the location of the HRIR file is shown on the top left of the UI in Output. But if I close the plugin UI and open it again, or if I close the project and open it again, the HRIR list is empty and shows "Load SOFA file" instead and "(no recently selectd files)" if I try expand the list.

It can be hard to know then if the SOFA file is loaded or not. Also, the path to the latest SOFA file loaded is not remembered by AmbiBIN, so if you want to load a new file after you have closed the UI or the project, you have to browse to the correct location again.

**Comment by leomccormack** [comment]
Ah yes! This is a minor annoyance, which I've not yet come up with a better solution for.  (Apologies, my UI design skills are rather limited!).

But if the "Use Default HRIRs" toggle button is not ticked, then the last loaded SOFA file should be in use. 
I would guess somehow saving/loading all past loaded SOFA files via the PluginProcessor::get/setStateInformation functions would be the way to have the plugin remember all of them.

**Comment by sguyader** [comment]
Thanks, now that I know that when the "Use Default HRIRs" checkbox is unticked, the last HRIR used is loaded, that's ok.
