### ISSUE TITLE
Crash in REAPER Linux when closing GUI

### ISSUE THREAD

**Issue by jpecquais** [leomccormack/SPARTA#50]
Hello,

In REAPER, Linux (Pop_OS), when the GUI of any plugin is close, REAPER crash.
This happen on the latest release of SPARTA plugin and REAPER 6.45.

Thank you for your help!

**Comment by muziker** [comment]
I'm using an older sparta plugin from july and it too crashes. One way of working around this is to try setting reaper to open generic UIs as default and switching to the GUI as needed, and switching back to the generic gui before closing any reaper FX windows.

**Comment by leomccormack** [comment]
OK. I believe this should now be fixed.
However, if the plugins still crash with the forthcoming v1.6.0 release, then please reopen this issue : )
