### ISSUE TITLE
beamforming

### ISSUE THREAD

**Issue by x3oo** [leomccormack/SPARTA#51]
can i use those plugins to use it as a beamforming microphone? maybe even with built in tracking?

**Comment by leomccormack** [comment]
Sure! The sparta_beamformer plugin accepts Ambisonic signals as input, and can give you up to 64 beamformers in the directions you choose.

If you're looking for source direction tracking, then maybe the compass_tracker plugin will do the trick? 
[https://leomccormack.github.io/sparta-site/docs/plugins/compass-suite/#tracker](https://leomccormack.github.io/sparta-site/docs/plugins/compass-suite/#tracker)

**Comment by tom-rod** [comment]
Hi @leomccormack ! I would like to know if there is, or if you have, a paper written on the development of the beamformer, or if you could simply explain how it was designed. What type of beamformer does it use? How are the different polar patterns achieved? What is the maxEV pattern? Thank you!
