### ISSUE TITLE
Sparta v1.5.2 crashes in reaper v6.45 in ubuntu

### ISSUE THREAD

**Issue by muziker** [leomccormack/SPARTA#52]
I've compiled Sparta v1.5.2 and it crashes in reaper v6.45 in ubuntu 20.04 when UI is being closed.  I've tried it with a few sparta plugins, and when the FX ui is closed, reaper crashes. Seems to work fine in carla though.

**Comment by muziker** [comment]
I've tried this using the default reaper FX ui and they work fine. It's definitely something with the UI

**Comment by PLu55** [comment]
I can confirm this problem with Sparta v1.5.2, downloaded binaries in Kubuntu 20.10. It's working with no problem in Ardour 6.9.0. Seems like a Reaper specific problem.

**Comment by leomccormack** [comment]
I believe this is now fixed in the forthcoming v1.6.0 release. However, please reopen the issue if the crashing persists : )
