### ISSUE TITLE
Building dirass sldoa and powermap

### ISSUE THREAD

**Issue by muziker** [leomccormack/SPARTA#6]
I'm having problems building these 3 plugins. First there isn't a makefile for them, and when projucer generates a makefile, i get:
`
Compiling PluginProcessor.cpp
In file included from ../../../../src/PluginProcessor.cpp:23:
../../../../src/PluginEditor.h:104:34: error: ‘CameraDevice’ has not been declared
     void cameraDeviceOpenResult (CameraDevice* device, const String& error);
`

when compiling this is on linux

**Comment by leomccormack** [comment]
Hi. Apologies for the (very) late reply! 
Unfortunately, this is a known issue on the JUCE side of things, so there hasn't been much we could do fix this. However, with the upcoming JUCE v6 release, (which appears to have improved Linux support), I'm hopeful that we'll be able to generate Linux makefiles for the visualisation plugins too in the near future :- )

**Comment by leomccormack** [comment]
JUCE v6 did not add camera support for linux in the end. Actually, the MacOSX camera device now behaves incorrectly...
(reported here: https://forum.juce.com/t/bug-in-macos-camera-device/40975) 

Perhaps a work-around where there can be both camera enabled and disabled versions of the plugin is the only way forward. 
This is difficult to do on the Projucer side, but now with CMake support... Perhaps.
