### ISSUE TITLE
None of the plugins will load in Reaper (v.1.6.1 & 1.6.2 – macOS)

### ISSUE THREAD

**Issue by lossius** [leomccormack/SPARTA#64]
I've had problems with installing v.1.6.1 and just tried installing v.1.6.2 and get the same problem there: None of the plugins load in Reaper.

<img width="939" alt="Screenshot 2022-06-20 at 17 52 09" src="https://user-images.githubusercontent.com/38478/174639457-a4e4b080-62ea-4345-80ab-0cacf8f6cee3.png">

Method to reproduce:

- Start Reaper with a new empty project
- Create a new track. (I also increased the number of channels on the track to 16)
- Click the FX button
- Within that window, click Add. From the list in the left panel, I chose `Developer > AALTO`, select all plugins listed and add them all.
- Result: All of them have a similar error message to what is displayed above.

Next, I tried to load the standalone application found in `/Applications/SPARTA/HOSIRR.app`. This resulted in a crash. I have uploaded the crash log here:

https://gist.github.com/lossius/8a4de8ac73789969ca6bbb8798050434

MacBook Pro (q6 inch, 2019)
2,4 GHz 8-Core Intel Core i9
macOS Monterey 12.4
Reaper v6.61 - June 17 2022

Cleaning out all plugins named `sparta_XXX` in `/Library/Audio/Plugins/VST` and then re-installing v. 1.6.0 brings them all back to life.

In all cases I have used the `(10.13+, x86-64) - (recommended for Intel CPUs)` installers.

**Comment by leomccormack** [comment]
hmm, could you please also try the ARM+x86 versions?

**Comment by lossius** [comment]
Sure! I just downloaded the ARM version of 1.6.2, cleaned out the plugins again, and installed. Now they all load in Reaper. So this is a problem with the Intell installer only.

**Comment by leomccormack** [comment]
> I have to say I've encountered the same issue with 1.6.1 and 1.6.2 x86-64 releases on macOS Big Sur 11.6.5 while 1.6.0 works fine (I am using notarised REAPER v6.59).

Thanks for letting me know. Do the ARM versions also work for you though?

**Comment by rapolasd** [comment]
> > I have to say I've encountered the same issue with 1.6.1 and 1.6.2 x86-64 releases on macOS Big Sur 11.6.5 while 1.6.0 works fine (I am using notarised REAPER v6.59).
> 
> Thanks for letting me know. Do the x86+ARM versions also work for you though?

Yes, they do.

**Comment by leomccormack** [comment]
OK, thanks! I won't be able to look into this right now, so I'll leave this issue open in the meantime in case it helps others. I've also now changed the 1.6.1 and 1.6.2 release pages to say that the x86+ARM versions are recommended for newer macOS versions.

**Comment by NicolaGiannini** [comment]
Hello, I don't know if that could help. 
I have the same issue with 1.61 and 1.62 (x86-64 version ). 
I’m on MacOS Mojave 10.14.6. 
MacBook Pro (15-inch, 2017), 2,9 GHz Intel Core i7.
The x86+ARM version seems to work for me too.

**Comment by michaeltrommer** [comment]
For the record – I have the same issue on MacOS Mojave 10.14.6. I've just installed the the x86+ARM version (even though it's listed as being for OS11 and above), however,  and everything seems to be OK so far.

**Comment by michaeltrommer** [comment]
Ah: not completely OK. The plug-ins (ARM version, though I'm on Intel 10.14.6) show up within an older Reaper project that they've already been inserted into, but If I try to load them into a new project they don't appear on the list of available plug-ins.

**Comment by enricofrancioni** [comment]
HI,
I will not open another topic, I think I fall into one of the cases reported above.
I installed MacOS (10.13+, x86-64) plugins on my MacBook Pro 10.15 Catalina (2.3 GHz Intel Core i5 quad core) at [link](https://github.com/leomccormack/SPARTA/releases/download /v1.6.2/MacOSX_SPARTA_2022_06_20_v1.6.2.pkg)
they are all in the /Library/Audio/Plug-Ins/VST/ folder of my note book, but my Reaper v5.987/64 won't open them.
Maybe I need to uninstall the plugins and upload another version?

**Comment by enricofrancioni** [comment]
HI,
I will not open another topic, I think I fall into one of the cases reported above.
I installed MacOS (10.13+, x86-64) plugins on my MacBook Pro 10.15 Catalina (2.3 GHz Intel Core i5 quad core) at [link](https://github.com/leomccormack/SPARTA/releases/download/v1.6.2/MacOSX_SPARTA_2022_06_20_v1.6.2.pkg)
they are all in the /Library/Audio/Plug-Ins/VST/ folder of my note book, but my Reaper v5.987/64 won't open them.
Maybe I need to uninstall the plugins and upload another version?

**Comment by leomccormack** [comment]
future releases will now be x86-64 and ARM combos, which don't exhibit this mysterious issue.
