### ISSUE TITLE
Array2SH: The spatial correlation graph looks different...

### ISSUE THREAD

**Issue by marclava** [leomccormack/SPARTA#65]
A screenshot of the spatial correlation graph for the eigenmike :
![image](https://user-images.githubusercontent.com/50078614/185770887-2721b619-9ef7-483a-8fd0-c821a275b48a.png)

It looks different than the one generated using the original MATLAB code 
(as seen at http://research.spa.aalto.fi/projects/spharrayproc-lib/spharrayproc.html) :
![image](https://user-images.githubusercontent.com/50078614/185770926-f91ab072-0453-4764-b70f-cea5dc08a91d.png)

Is it different? If so, is there a reason to be worried?

**Comment by motherlessdeer** [comment]
Hi there!
I was just wondering if you have any experience with the Sparta plugins!
If so, please let me know!
Thanks

**Comment by leomccormack** [comment]
Interesting! I hadn't spotted this. I would guess that it just comes down to how the arrays are being modelled at low frequencies.

However, I don't think you should be worried. These correlation graphs should be interpreted alongside the level difference plots:
![Screenshot 2023-01-30 at 14 30 54](https://user-images.githubusercontent.com/36531075/215477665-ff71afc3-bc3c-4f9f-8299-3ffbaa56cc30.jpg)
![Screenshot 2023-01-30 at 14 30 40](https://user-images.githubusercontent.com/36531075/215477675-f941ffd1-5e0b-495d-8af2-446628801b72.jpg)
From which, the conclusions regarding the approximate usable bandwidths remain the same across both of these implementations (i.e. using the correlation graphs to find the upper frequency limit/aliasing frequencies, and the level difference graphs for finding the lower frequency limit). 

But I will add it to the list to look into why this happens exactly. Thank you for bringing it up! : )
