### ISSUE TITLE
macOS Package Receipt 

### ISSUE THREAD

**Issue by paul-cossey** [leomccormack/SPARTA#66]
Hi, @leomccormack 

We're looking to deploy SPARTA to some of our education customers. 

We have an issue where we can't deploy SPARTA without repackaging it. The tooling we use to automatically download and install (AutoPkg, Munki, Jamf Pro) needs a way to know that the version has been updated, and to install that latest version. One common way is looking at package receipts for this. 

Would it be possible for you to bump the package receipt version number when you release a new version so that they match? Currently the package receipt is on version 1.0 but the actual release number is 1.6.2 

` pkg-ref id="com.sparta.pkg." version="1.0" auth="Root"` would become  `pkg-ref id="com.sparta.pkg." version="1.6.2" auth="Root"`

Thanks for your consideration, and please let me know if you want any further clarification 

Paul

**Comment by leomccormack** [comment]
Good point. Done!
This should take effect for future releases.

**Comment by paul-cossey** [comment]
Thank you!
