### ISSUE TITLE
I forked SPARTA and SAF to compile LV2 versions of the plugins

### ISSUE THREAD

**Issue by marclava** [leomccormack/SPARTA#68]
https://github.com/marclava/SPARTA/tree/lv2

Ideally there would be a method to configure the build for VST and/or LV2. But I'm glad it works!

**Comment by leomccormack** [comment]
I'm also glad to hear that it works! 

I think adding an input CMake message to dictate which plugin formats should be built, makes a lot of sense. 

I'll look into it.

**Comment by leomccormack** [comment]
Added the following options:
`-DSPARTA_BUILD_VST3=1
-DSPARTA_BUILD_LV2=1`
