### ISSUE TITLE
v1.6.2 - missing plugins?

### ISSUE THREAD

**Issue by ariutti** [leomccormack/SPARTA#69]
Hi everyone,
I recently installed the 1.6.2 version of the plugins downloading the .zip file on my Linux Ubuntu Studio 22.04 distribution.
I'm using them on my Reaper 6.66.

It seems to me that, inside the zip package, some plugin file is missing. Talking about:

- `SPARTA - DirASS`;
- `SPARTA - PowerMap`;
- `SPARTA - SLDoA`;
- `HO-DirAC - Decoder`;
- `HO-DirAC - upmixer`;

Even if they are documented on the [reference page](https://leomccormack.github.io/sparta-site/docs/plugins/overview/).

On the other hand, I noticed that among the available plugins there is also the "`SPARTA PitchShifter`", which is not listed on the documentation page.

Maybe I should download the missing plugins in another mode?
Thank you so much for your support

**Comment by leomccormack** [comment]
Ah yes, those 3 sparta visualisation plugins are not supported on linux, since JUCE does not support certain functionality for them. As for the 2 DirAC plugins, that's strange. I'll look into what happened there. 

I'll also try to add a PitchShifter plugin description to the website soon.
