### ISSUE TITLE
Sparta Plugins don't work on Macbook Pro M1 on Ventura - DAW Logic X Pro

### ISSUE THREAD

**Issue by pflying64** [leomccormack/SPARTA#77]
Hello, I have successfully downloaded your VST3 plugins for Mac Os Arm-x86, and the installation process went smoothly. 
All the plugins are in the correct folder, where all the other working plugins for Logic are also located. 
When I launch Logic X Pro, unlike when I install a new plugin, the window for scanning new plugins does not appear. 
It simply ignores them.
I've checked in the plugin manager, and your plugins do not appear at all.
I've tried forcing a reset of the audio unit and performing a complete rescan, but... nothing.
Just to clarify: it's not that the plugins are present in the plugin manager and marked as incompatible. 
They are simply not there.

Macbook Pro M1
macOS 13.5.1 
Logic 10.7.9

I'm very interested in trying out your plugins; can you help me figure this out?
Thanks in advance,
Paolo

**Comment by leomccormack** [comment]
Hi.
I was under the impression that Logic unfortunately does not support VST plugins? I will, however, look at implementing an option to compile AU versions of the plugins. Although, I have no idea how well/badly Logic handles multi-channel plugins such as these.

**Comment by leomccormack** [comment]
The latest master branch now supports adding the CMake option: "-DBUILD_PLUGIN_FORMAT_AU"
I won't build these versions for the official releases, as I don't have a Logic license to test them, but hopefully other now can : )
